// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbvrsicljfbuklpigkgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidnJzaWNsamZidWtscGlna2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Mjc5NDcsImV4cCI6MjA3MjQwMzk0N30.oYuuQJA2Mu5lX7A6E-ZYP0T-5Qu7CxU_7Y4DmWE_z6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});